runtime: go
api_version: go1
threadsafe: yes

default_expiration: 1d

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 300

handlers:
- url: /(.+\.(ico|txt))$
  static_files: app/\1
  upload: app/(.+\.(ico|txt))$
  secure: always
- url: /(.+(\.js|\.css))$
  static_files: app/\1
  upload: app/(.+(\.js|\.css))$
  expiration: 10m
  secure: always
- url: /(.+\.html)$
  static_files: app/\1
  upload: app/.+\.html$
  application_readable: true
  secure: always
- url: /.*
  script: _go_app
  secure: always